config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }

  devise_scope :user do
    post 'users/sign_up', to: 'users/registrations#create'
    get 'users/registrations/complete/:id', to: 'users/registrations#details', as: :complete_user_registration
    put 'users/registrations/complete/:id', to: 'users/registrations#complete'
  end

  root to: 'organisations#index'

  resources :organisations do
    resources :teams, except: %i[index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/organisation.rb
# frozen_string_literal: true

class Organisation < ApplicationRecord
  has_many :teams, dependent: :destroy
end

app/controllers/organisations_controller.rb
# frozen_string_literal: true

class OrganisationsController < ApplicationController
  before_action :set_organisation, only: %i[show edit update destroy]

  add_breadcrumb 'Organisations', :organisations_path
  add_breadcrumb :current_organisation_name, :current_organisation, only: %i[show edit]
  add_breadcrumb 'New organisation', nil, only: %i[new create]
  add_breadcrumb 'Edit', nil, only: :edit

  def index
    @organisations = Organisation.all
  end

  def show; end

  def new
    @organisation = Organisation.new
  end

  def edit; end

  def create
    @organisation = Organisation.new(organisation_params)

    if @organisation.save
      redirect_to @organisation, notice: 'Organisation was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /organisations/1 or /organisations/1.json
  def update
    if @organisation.update(organisation_params)
      redirect_to @organisation, notice: 'Organisation was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /organisations/1 or /organisations/1.json
  def destroy
    @organisation.destroy
    redirect_to organisations_url, notice: 'Organisation was successfully destroyed.'
  end

  private

  def set_organisation
    @organisation = Organisation.find(params[:id])
  end

  def organisation_params
    params.require(:organisation).permit(:name)
  end

  def current_organisation
    @current_organisation ||= Organisation.find(params[:id])
  end

  def current_organisation_name
    current_organisation.name
  end

  helper_method :current_organisation, :current_organisation_name
end

app/views/organisations/_form.html.erb
<div class="row">
  <div class="col-12 col-lg-4 offset-lg-4">
    <%= simple_form_for(organisation) do |form| %>
      <%= form.input :name %>
      <div class="mt-5 text-center">
        <%= link_to 'Cancel', organisations_path, class: 'btn btn-secondary', data: { confirm: 'Are you sure you want to quit?' } %>
        <%= form.button :submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/organisations/edit.html.erb
<% provide :page_title do %>
  Editing Organisation
<% end %>

<%= render 'form', organisation: @organisation %>

app/views/organisations/index.html.erb
<% provide :page_title do %>
  Organisations
<% end %>

<% provide :page_cta do %>
  <%= link_to 'New Organisation', new_organisation_path, class: 'btn btn-primary' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <tr data-test-id="organisation_<%= organisation.id %>_row">
        <td><%= organisation.name %></td>
        <td><%= link_to 'Show', organisation %></td>
        <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
        <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/organisations/new.html.erb
<% provide :page_title do %>
  New Organisation
<% end %>

<%= render 'form', organisation: @organisation %>

app/views/organisations/show.html.erb
<% provide :page_title do %>
  <%= @organisation.name %>
<% end %>

<% provide :page_cta do %>
  <%= link_to 'Edit Organisation', edit_organisation_path(@organisation), class: 'btn btn-primary' %>
<% end %>

<div class="row">
  <div class="col-12">
    <div class="row mb-3">
      <div class="col-6"><h2>Teams</h2></div>
      <div class="col-6 d-flex text-end align-items-center">
        <div class="w-100"><%= link_to 'New Team', new_organisation_team_path(@organisation), class: 'btn btn-success' %></div>
      </div>
    </div>
    <%= render 'teams/teams_list', organisation: @organisation, teams: @organisation.teams %>
  </div>
<div>